#!/bin/sh

# ----------------------------------------------------------------------
#
# 2023-02-12: Update with OpenSP
#
# ----------------------------------------------------------------------


SGMLS=onsgmls
SGMLSASP=sgmlsasp

INPUT=$1
OUTPUT=`echo $INPUT | sed 's/.sgml/.html/'`

# SGML_PATH=$PWD/%N.dtd:$PWD/%P.dtd:$PWD/htm/%N

SGML_PATH=$PWD/html/%N:$PWD/%N.dtd:$PWD/%P.dtd
export SGML_PATH

SP_CHARSET_FIXED=1 SP_ENCODING=UTF-8 $SGMLS -D $PWD/html dqmm.decl $INPUT | $SGMLSASP $PWD/html/mapping > $OUTPUT
